### ISSUE TITLE
please add Onkyo tx-nr575e

### ISSUE THREAD

**Issue by thechris1992** [ToddGreenfield/homebridge-onkyo#31]
https://www.ch.onkyo.com/de/produkte/tx-nr575e-137837.html

**Comment by cbrandlehner** [comment]
Most Onkyo receivers work when using the configuration of a model 'near' to the actual model number.
Most users are successful using TX-NR609.

Which ones have you tried and what were the issues you were facing?

**Comment by thechris1992** [comment]
Hey, there are some channels like streambox who are Not Supported by the nr609..

**Comment by thechris1992** [comment]
Still supported or end of support?

**Comment by ToddGreenfield** [comment]
Not supported by me anymore. No more Onkyo  and no time. I believe a couple others are supporting it. If anyone wants to help with maintaining let me know.

**Comment by solowalker27** [comment]
Model support isn’t handled by this repo. We’d have to fork and maintain https://github.com/tillbaks/node-eiscp in order to add new models as that’s the module we depend on for the actual communication with the devices. Without having already looked at both the code and the 575e, I don’t know how much work that would be. If it’s just adding the model to a model group, it wouldn’t be so bad. If it’s updating the code to support new features, that’d be impossible unless one of us buys a new model. And that’s assuming we have the time. @thechris1992 you could fork the repo and figure out how it works and add the support and then we could look into changing our dependency to your fork.
