### ISSUE TITLE
Won't install on HOOBS 3

### ISSUE THREAD

**Issue by kassie76** [ToddGreenfield/homebridge-onkyo#38]
I try to install this plugin by HOOBS 3-versie. 3.1.10
But it doesn't show up in installed plugins

I use a Raspberry 3b

**Comment by iondarie** [comment]
before trying to install run: sudo journalctl -f -u hoobs from the terminal then try to install and you will see It gives error: "undefined ls-remote -h -t git://github.com/tillbaks/node-eiscp.git".

The error can be fixed by installing git:

sudo apt-get install git

After that install the plugin, and it will work. I just installed it 3 minutes ago runing latest version of HOOBS

**Comment by kassie76** [comment]
This solves the problem, thanks
